### ISSUE TITLE
use jshint to make sure your code is standard

### ISSUE THREAD

**Issue by twilson63** [mwdion/NumGuessGameJS#12]
``` sh
npm install jshint -g
jshint app.js
```

**Comment by mwdion** [comment]
Wow that showed me about 8 changes I should make.  Thanks.

**Comment by twilson63** [comment]
Yea there are ways to automate it into your workflow using tools like
pre-commit but it is good to run manually too!

:-)

Thanks

Tom

On Wed, Feb 11, 2015 at 4:18 PM, Michael Dion notifications@github.com
wrote:

> Wow that showed me about 8 changes I should make. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mwdion/NumGuessGameJS/issues/12#issuecomment-73966742
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
